version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    env_file:
      - hadoop.env
    networks:
      - hadoop-network
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - ./data:/data
    environment:
      - CLUSTER_NAME=lab2
    deploy:
      resources:
        limits:
          memory: 4G

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    env_file:
      - hadoop.env
    networks:
      - hadoop-network
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      resources:
        limits:
          memory: 4G

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    env_file:
      - hadoop.env
    networks:
      - hadoop-network
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      resources:
        limits:
          memory: 4G

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    env_file:
      - hadoop.env
    networks:
      - hadoop-network
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  hadoop-network:
    driver: bridge
    name: hadoop-network