version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"   # Hadoop UI
      - "8020:8020"   # HDFS
    volumes:
      - ./data:/data
    environment:
      - CLUSTER_NAME=lab2
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - hadoop-network

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    env_file:
      - hadoop.env
    networks:
      - hadoop-network
    depends_on:
      - namenode
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  hadoop-network:
    driver: bridge
    name: hadoop-network